/* eslint-disable prefer-const */
/* eslint-disable max-len */

/** @type{ {common-name: String, scientific-name: String, family: String, description: String}[] } */
export let names = [
  {'common-name': 'False \'ohe',
    'scientific-name': 'Munroidendron racemosum (Forbes) Sherff',
    'family': 'Araliaceae',
    'description': 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\n Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.'},
  {'common-name': 'Lowland Beardtongue',
    'scientific-name': 'Penstemon alluviorum Pennell',
    'family': 'Scrophulariaceae',
    'description': 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.'},
  {'common-name': 'Dwarf Red Blackberry',
    'scientific-name': 'Rubus pubescens Raf.',
    'family': 'Rosaceae',
    'description': 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.'},
  {'common-name': 'Tickbush',
    'scientific-name': 'Kunzea ambigua (Sm.) Druce',
    'family': 'Myrtaceae',
    'description': 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'},
  {'common-name': 'Dicranum Moss',
    'scientific-name': 'Dicranum Hedw.',
    'family': 'Dicranaceae',
    'description': 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.'},
  {'common-name': 'Dot Lichen',
    'scientific-name': 'Arthonia lapidicola (Taylor) Branth & Rostrup',
    'family': 'Arthoniaceae',
    'description': 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.'},
  {'common-name': 'Snake Canyon Milkvetch',
    'scientific-name': 'Astragalus vallaris M.E. Jones',
    'family': 'Fabaceae',
    'description': 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.'},
  {'common-name': 'Hoover\'s Cryptantha',
    'scientific-name': 'Cryptantha hooveri I.M. Johnst.',
    'family': 'Boraginaceae',
    'description': 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.'},
  {'common-name': 'Short\'s Spreading Chervil',
    'scientific-name': 'Chaerophyllum procumbens (L.) Crantz var. shortii Torr. & A. Gray',
    'family': 'Apiaceae',
    'description': 'Sed ante. Vivamus tortor. Duis mattis egestas metus.'},
  {'common-name': 'Mustang Monardella',
    'scientific-name': 'Monardella lanceolata A. Gray var. lanceolata',
    'family': 'Lamiaceae',
    'description': 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.'},
  {'common-name': 'Mojave Thistle',
    'scientific-name': 'Cirsium mohavense (Greene) Petr.',
    'family': 'Asteraceae',
    'description': 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'},
];
